spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/eshop_db
    username: bestuser
    password: bestuser
  flyway:
    baseline-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: anton.hulevich.for.work@gmail.com
    password: "siydrnpfshcsaudm"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true
server:
  hostname: localhost
  port: ${PORT:8080}
logging:
  level:
    root: info
    com.antonhulevich.eshop.aspect: debug
  file:
    name: logs/eshop-application.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/archived/eshop-%d{yyyy-MM-dd}.%i.log.gz
      max-file-size: 10MB
      max-history: 1
      total-size-cap: 2GB
  pattern:
    console: "%clr(%d{yyyy-MM-DD HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
